class StaticSort:
    def sort_method_1(self, array: list[int]) -> list[int]:
        ...

    def sort_method_2(self, array: list[int]) -> list[int]:
        ...
    
    def sort_method_3(self, array: list[int]) -> list[int]:
        ...
    
    def sort_method_4(self, array: list[int]) -> list[int]:
        ...

    def sort_method_5(self, array: list[int]) -> list[int]:
        ...

    def sort_method_6(self, array: list[int]) -> list[int]:
        ...
    
    def sort_method_7(self, array: list[int]) -> list[int]:
        ...
    
    def sort_method_8(self, array: list[int]) -> list[int]:
        ...
